# Generated by Django 6.0.3 on 2026-03-29 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description_note', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priorite', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('max_capacite', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='garage.demande')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.garage'),
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('type_intervention', models.CharField(max_length=100, verbose_name='Type of Service')),
                ('description_travaux', models.TextField(verbose_name='Work Description')),
                ('diagnostic', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='planned', max_length=20)),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kilometrage', models.IntegerField(default=0, verbose_name='Mileage at Service')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='garage.demande')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(upload_to='interventions/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='garage.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('statut', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('tva_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='VAT %')),
                ('notes', models.TextField(blank=True)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='garage.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mecaniciens', to='garage.garage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mecanicien', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intervention',
            name='mecanicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='garage.mecanicien'),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='garage.garage')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.IntegerField(default=1)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_pieces', to='garage.intervention')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.piece')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('codes_defaut', models.TextField(blank=True, verbose_name='Fault Codes')),
                ('observations', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='garage.demande')),
                ('mecanicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='garage.mecanicien')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='License Plate')),
                ('marque', models.CharField(max_length=100, verbose_name='Brand')),
                ('modele', models.CharField(max_length=100, verbose_name='Model')),
                ('annee', models.IntegerField(verbose_name='Year')),
                ('kilometrage_actuel', models.IntegerField(verbose_name='Current Mileage (km)')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='garage.garage')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='garage.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateTimeField(verbose_name='Appointment Date & Time')),
                ('motif', models.CharField(max_length=200, verbose_name='Reason for Visit')),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.garage')),
                ('mecanicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='garage.mecanicien')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='garage.vehicule')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_rdv'],
            },
        ),
        migrations.AddField(
            model_name='demande',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='garage.vehicule'),
        ),
    ]
