# Generated by Django 6.0.3 on 2026-05-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Task Description')),
                ('est_terminee', models.BooleanField(default=False, verbose_name='Is Completed?')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='garage.intervention')),
            ],
        ),
    ]
