# Generated by Django 6.0.3 on 2026-05-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_tacheintervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacheintervention',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gain Mécanicien'),
        ),
    ]
