# Generated by Django 6.0.3 on 2026-05-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_tacheintervention_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_estimee_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Completion'),
        ),
        migrations.AddField(
            model_name='piece',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pieces/', verbose_name='Part Photo'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicules/', verbose_name='Vehicle Photo'),
        ),
    ]
