# Generated by Django 6.0.3 on 2026-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_intervention_date_estimee_fin_piece_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='problemes_futurs',
            field=models.TextField(blank=True, null=True, verbose_name='Future Potential Issues'),
        ),
    ]
